cmsShoppingCart/Areas/Admin/Controllers/CategoriesController.cs
using cmsShoppingCart.Infrastructure;
using cmsShoppingCart.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System.Linq;
using System.Threading.Tasks;

namespace cmsShoppingCart.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CategoriesController : Controller
	{
		private readonly shoppingCartDbContext context;
		public CategoriesController(shoppingCartDbContext context)
		{
			this.context = context;
		}
		//GET admin/categories
		public async Task<IActionResult> Index()
		{
			return View(await context.Categories.OrderBy(x=>x.Sorting).ToListAsync());
		}

		//GET admin/categories/create
		public IActionResult Create() => View();

		//POST admin/categories/create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(Category category)
		{
			if (ModelState.IsValid)
			{
				category.Slug = category.Name.ToLower().Replace(" ", "-");
				category.Sorting = 100;

				var slug = context.Categories.FirstOrDefault(x => x.Slug == category.Slug);
				if (slug != null)
				{
					ModelState.AddModelError("", "The category is already exists.");
					return View(category);
				}
				context.Add(category);
				await context.SaveChangesAsync();

				TempData["Success"] = "The category has been added!";

				return RedirectToAction("Index");
			}
			return View(category);
		}


		//GET admin/category/edit/5
		public async Task<ActionResult> Edit(int id)
		{
			Category category = await context.Categories.FindAsync(id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}

		//POST admin/category/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(int id, Category category)
		{
			if (ModelState.IsValid)
			{
				category.Slug = category.Id == 1 ? "home" : category.Name.ToLower().Replace(" ", "-");

				var slug = context.Categories.Where(x => x.Id != id).FirstOrDefault(x => x.Slug == category.Slug);
				if (slug != null)
				{
					ModelState.AddModelError("", "The category is already exists.");
					return View(category);
				}
				context.Update(category);
				await context.SaveChangesAsync();

				TempData["Success"] = "The category has been Edited!";

				return RedirectToAction("Edit", new { id });
			}
			return View(category);
		}

		//GET admin/category/delete/5
		public async Task<ActionResult> Delete(int id)
		{
			Category category = await context.Categories.FindAsync(id);
			if (category == null)
			{
				TempData["Error"] = "The page does not exist!";
			}
			else
			{
				context.Categories.Remove(category);
				await context.SaveChangesAsync();

				TempData["Success"] = "The category has been deleted!";
			}
			return RedirectToAction("Index");
		}
		public async Task<ActionResult> Details(int id)
		{
			Category category = await context.Categories.FirstOrDefaultAsync(x => x.Id == id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}

		//POST admin/categories/reorder
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Reorder(int[] id)
		{
			int count = 1;

			foreach (var pageId in id)
			{
				Category category = await context.Categories.FindAsync(pageId);
				category.Sorting = count;
				context.Update(category);
				await context.SaveChangesAsync();
				count++;
			}
			return Ok();
		}

	}
}

cmsShoppingCart/Areas/Admin/Controllers/PagesController.cs
using cmsShoppingCart.Infrastructure;
using cmsShoppingCart.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cmsShoppingCart.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class PagesController : Controller
	{
		private readonly shoppingCartDbContext context;
		public PagesController(shoppingCartDbContext context)
		{
			this.context = context;
		}

		//GET admin/pages
		public async Task<ActionResult> Index()
		{
			IQueryable<Page> pages = from p in context.Pages
															 orderby p.Sorting
															 select p;

			List<Page> pageList = await pages.ToListAsync();
			return View(pageList);
		}
		//GET admin/pages/details/5
		public async Task<ActionResult> Details(int id)
		{
			Page page = await context.Pages.FirstOrDefaultAsync(x => x.Id == id);
			if (page == null)
			{
				return NotFound();
			}
			return View(page);
		}

		//GET admin/pages/create
		public IActionResult Create() => View();


		//POST admin/pages/create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(Page page)
		{
			if (ModelState.IsValid)
			{
				page.Slug = page.Title.ToLower().Replace(" ", "-");
				page.Sorting = 100;

				var slug = context.Pages.FirstOrDefault(x => x.Slug == page.Slug);
				if (slug != null)
				{
					ModelState.AddModelError("", "The category is already exists.");
					return View(page);
				}
				context.Add(page);
				await context.SaveChangesAsync();

				TempData["Success"] = "The category has been added!";

				return RedirectToAction("Index");
			}
			return View(page);
		}


		//GET admin/pages/edit/5
		public async Task<ActionResult> Edit(int id)
		{
			Page page = await context.Pages.FindAsync(id);
			if (page == null)
			{
				return NotFound();
			}
			return View(page);
		}

		//POST admin/pages/Edit
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(Page page)
		{
			if (ModelState.IsValid)
			{
				page.Slug = page.Id == 1 ? "home" : page.Title.ToLower().Replace(" ", "-");
				
				var slug = context.Pages.Where(x=>x.Id != page.Id).FirstOrDefault(x => x.Slug == page.Slug);
				if (slug != null)
				{
					ModelState.AddModelError("", "The page is already exists.");
					return View(page);
				}
				context.Update(page);
				await context.SaveChangesAsync();

				TempData["Success"] = "The page has been Edited!";

				return RedirectToAction("Edit",new { id = page.Id});
			}
			return View(page);
		}

		//GET admin/pages/delete/5
		public async Task<ActionResult> Delete(int id)
		{
			Page page = await context.Pages.FindAsync(id);
			if (page == null)
			{
				TempData["Error"] = "The page does not exist!";
			}
			else
			{
				context.Pages.Remove(page);
				await context.SaveChangesAsync();

				TempData["Success"] = "The page has been deleted!";
			}
			return RedirectToAction("Index");
		}

		//POST admin/pages/reorder
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Reorder(int[] id)
		{
			int count = 1;
			
			foreach(var pageId in id)
			{
				Page page = await context.Pages.FindAsync(pageId);
				page.Sorting = count;
				context.Update(page);
				await context.SaveChangesAsync();
				count++;
			}
			return Ok();
		}
	}
}

cmsShoppingCart/Areas/Admin/Controllers/ProductsController.cs
using cmsShoppingCart.Infrastructure;
using cmsShoppingCart.Models;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace cmsShoppingCart.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class ProductsController : Controller
	{
		private readonly shoppingCartDbContext context;
		private readonly IWebHostEnvironment webHostEnvironment;
		public ProductsController(shoppingCartDbContext context)
		{
			this.context = context;
			this.webHostEnvironment = webHostEnvironment;
		}

		//GET admin/products
		public async Task<IActionResult> Index(int p=1)
		{
			int pageSize = 5;
			var products = context.Products.OrderByDescending(x => x.Id)
																		.Include(x => x.Category)
																		.Skip((p-1)*pageSize)
																		.Take(pageSize);

			ViewBag.PageNumber = p;
			ViewBag.PageRange = pageSize;
			ViewBag.TotalPages = (int)Math.Ceiling((decimal)context.Products.Count() / pageSize);

			return View(await products.ToListAsync());
		}

		//GET admin/products/create
		public IActionResult Create()
		{
			ViewBag.CategoryId = new SelectList(context.Categories.OrderBy(x => x.Sorting), "Id", "Name");

			return View();
		}


		//POST admin/products/create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(Product product)
		{
			if (ModelState.IsValid)
			{
				product.Slug = product.Name.ToLower().Replace(" ", "-");

				var slug = context.Products.FirstOrDefault(x => x.Slug == product.Slug);
				if (slug != null)
				{
					ModelState.AddModelError("", "The product is already exists.");
					return View(product);
				}


				string imageName = "noimage.png";
				if(product.ImageUpload != null)
				{
					string uploadsDir = Path.Combine(webHostEnvironment.WebRootPath, "media/products");
					imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload.FileName;
					string filePath = Path.Combine(uploadsDir, imageName);
					FileStream fs = new FileStream(filePath,FileMode.Create);
					await product.ImageUpload.CopyToAsync(fs);
					fs.Close();
				}
				product.Image = imageName;
				context.Add(product);
				await context.SaveChangesAsync();

				TempData["Success"] = "The product has been added!";

				return RedirectToAction("Index");
			}
			return View(product);
		}
	}
}

cmsShoppingCart/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/" 
                target="_blank">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pages" asp-action="Index">Pages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

cmsShoppingCart/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if(TempData["Success"] != null)
{
	<div class="alert alert-success notification">
		@TempData["Success"]
	</div>
}

@if(TempData["Error"] != null)
{
	<div class="alert alert-danger notification">
		@TempData["Error"]
	</div>
}